title: Weasel - Web-application testing with Perl
description: Bridging the gap between Page Objects and your web testing library
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
